"""add_columner

Revision ID: 1bef8bed859a
Revises: cd43678ba307
Create Date: 2025-04-09 17:39:47.689937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bef8bed859a'
down_revision: Union[str, None] = 'cd43678ba307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'currency',
               existing_type=postgresql.ENUM('USDT', 'BNB', 'ETH', 'TON', 'BTC', name='currency_enum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rate', 'currency',
               existing_type=sa.String(),
               type_=postgresql.ENUM('USDT', 'BNB', 'ETH', 'TON', 'BTC', name='currency_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
