"""recreate_tables

Revision ID: 98cb6df8720b
Revises: 
Create Date: 2025-04-09 12:42:02.587528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cb6df8720b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('ton_secret_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('btc_secret_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('eth_secret_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('bsc_secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'bsc_secret_key')
    op.drop_column('wallet', 'eth_secret_key')
    op.drop_column('wallet', 'btc_secret_key')
    op.drop_column('wallet', 'ton_secret_key')
    # ### end Alembic commands ###
